src/Entity/Kind.php
<?php

namespace App\Entity;

use ContainerM8BJPEV\getDoctrine_Orm_DefaultEntityManager_PropertyInfoExtractorService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Migrations\Configuration\EntityManager\ExistingEntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Table]
#[ORM\Index(name: 'idx_tracing', columns: ['tracing'])]
#[ORM\Entity(repositoryClass: \App\Repository\KindRepository::class)]
class Kind
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\JoinColumn(nullable: false)]
    #[ORM\ManyToOne(targetEntity: \App\Entity\Stammdaten::class, inversedBy: 'kinds')]
    private $eltern;

    #[ORM\Column(type: 'text', nullable: true)]
    private $allergie;

    #[ORM\Column(type: 'text', nullable: true)]
    private $medikamente;

    #[Assert\NotBlank]
    #[ORM\Column(type: 'text', nullable: true)]
    private $vorname;

    #[Assert\NotBlank]
    #[ORM\Column(type: 'text', nullable: true)]
    private $nachname;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $klasse;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $art;

    #[Assert\NotBlank]
    #[ORM\Column(type: 'datetime')]
    private $geburtstag;


    #[ORM\OneToMany(targetEntity: \App\Entity\Abwesend::class, mappedBy: 'kind')]
    private $abwesends;

    #[ORM\ManyToMany(targetEntity: \App\Entity\Zeitblock::class, mappedBy: 'kind')]
    private $zeitblocks;

    #[ORM\Column(type: 'text', nullable: true)]
    private $bemerkung;

    #[ORM\JoinColumn(nullable: true)]
    #[ORM\ManyToOne(targetEntity: \App\Entity\Schule::class, inversedBy: 'kinder')]
    private $schule;

    #[ORM\Column(type: 'boolean')]
    private $fin = false;

    #[ORM\Column(type: 'boolean')]
    private $gluten = false;

    #[ORM\Column(type: 'boolean')]
    private $laktose = false;

    #[ORM\Column(type: 'boolean')]
    private $schweinefleisch = false;

    #[ORM\Column(type: 'boolean')]
    private $vegetarisch = false;

    #[ORM\Column(type: 'boolean')]
    private $ausfluege = false;

    #[ORM\Column(type: 'boolean')]
    private $alleineHause = false;

    #[ORM\Column(type: 'boolean')]
    private $sonnencreme = false;

    #[ORM\Column(type: 'boolean')]
    private $fotos = false;

    #[ORM\ManyToMany(targetEntity: \App\Entity\Zeitblock::class, inversedBy: 'kinderBeworben')]
    private $beworben;

    #[ORM\Column(type: 'boolean')]
    private $saved = false;

    #[ORM\Column(type: 'integer')]
    private $history = 0;

    #[ORM\Column(type: 'string', nullable: true)]
    private $tracing;

    #[ORM\ManyToMany(targetEntity: \App\Entity\Rechnung::class, mappedBy: 'kinder')]
    private $rechnungen;


    #[ORM\OneToMany(targetEntity: \App\Entity\KindFerienblock::class, mappedBy: 'kind', cascade: ['remove'])]
    private $kindFerienblocks;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $masernImpfung;

    #[ORM\OneToMany(targetEntity: \App\Entity\Anwesenheit::class, mappedBy: 'kind')]
    private $anwesenheitenSchulkindbetreuung;

    #[ORM\Column(type: 'text', nullable: true)]
    private $internalNotice;

    #[ORM\Column(type: 'date', nullable: true)]
    private $startDate;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $zeckenEntfernen;

    #[ORM\ManyToMany(targetEntity: Zeitblock::class, inversedBy: 'wartelisteKinder')]
    #[ORM\JoinTable(name: 'kinder__warteliste')]
    #[ORM\JoinColumn(name: 'kind_id', referencedColumnName: 'id')]
    #[ORM\InverseJoinColumn(name: 'zeitblock_id', referencedColumnName: 'id')]
    private Collection $warteliste;

    #[ORM\ManyToMany(targetEntity: Zeitblock::class, inversedBy: 'movedToWaitingKid')]
    #[ORM\JoinTable(name: 'kinder___moved_to_warteliste')]
    #[ORM\JoinColumn(name: 'kind_id', referencedColumnName: 'id')]
    #[ORM\InverseJoinColumn(name: 'zeitblock_id', referencedColumnName: 'id')]
    private Collection $movedToWaiting;


    public function __serialize(): array
    {
        return $this->tracing;
    }

    public function __toString()
    {
        return $this->tracing;
    }

    public function __clone()
    {
        $this->zeitblocks = new ArrayCollection();
        $this->beworben = new ArrayCollection();
        $this->warteliste = new ArrayCollection();
        $this->id = null;
    }

    public function __construct()
    {
        $this->zeitblocks = new ArrayCollection();
        $this->abwesends = new ArrayCollection();
        $this->beworben = new ArrayCollection();
        $this->rechnungen = new ArrayCollection();
        $this->ferienProgrammBeworben = new ArrayCollection();
        $this->ferienProgrammGebucht = new ArrayCollection();
        $this->ferienProgrammBezahlt = new ArrayCollection();
        $this->ferienProgrammStorniert = new ArrayCollection();
        $this->kindFerienblocks = new ArrayCollection();
        $this->anwesenheitenSchulkindbetreuung = new ArrayCollection();
        $this->warteliste = new ArrayCollection();
        $this->movedToWaiting = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEltern(): ?Stammdaten
    {
        return $this->eltern;
    }

    public function setEltern(?Stammdaten $eltern): self
    {
        $this->eltern = $eltern;

        return $this;
    }

    public function getAllergie(): ?string
    {
        return $this->allergie;
    }

    public function setAllergie(?string $allergie): self
    {
        $this->allergie = $allergie;

        return $this;
    }

    public function getMedikamente(): ?string
    {
        return $this->medikamente;
    }

    public function setMedikamente(?string $medikamente): self
    {
        $this->medikamente = $medikamente;

        return $this;
    }

    public function getVorname(): ?string
    {
        return $this->vorname;
    }

    public function setVorname(?string $vorname): self
    {
        $this->vorname = $vorname;

        return $this;
    }

    public function getNachname(): ?string
    {
        return $this->nachname;
    }

    public function setNachname(?string $nachname): self
    {
        $this->nachname = $nachname;

        return $this;
    }

    public function getKlasse(): ?int
    {
        return $this->klasse;
    }

    public function getKlasseString(): ?string
    {
        $klassArr = $this->schule->getStadt()->translate()->getSettingsSkibShoolyearNamingArray();
        try {
            return $klassArr[$this->klasse];
        } catch (\Exception $exception) {
            return 'error! Contact the Administrator';
        }

    }

    public function setKlasse(?int $klasse): self
    {
        $this->klasse = $klasse;

        return $this;
    }

    public function getArt(): ?int
    {
        return $this->art;
    }

    public function setArt(?int $art): self
    {
        $this->art = $art;

        return $this;
    }

    public function getGeburtstag(): ?\DateTimeInterface
    {
        return $this->geburtstag;
    }

    public function setGeburtstag(\DateTimeInterface $geburtstag): self
    {
        $this->geburtstag = $geburtstag;

        return $this;
    }

    /**
     * @return Collection|Zeitblock[]
     */
    public function getZeitblocks(): Collection
    {

        return $this->zeitblocks;
    }

    /**
     * @return Collection|Zeitblock[]
     */
    public function getRealZeitblocks(): Collection
    {
        $block = array();
        foreach ($this->zeitblocks->toArray() as $data) {
            if (!$data->getDeleted()) {
                $block[] = $data;
            }
        }

        usort($block, function (Zeitblock $a, Zeitblock $b) {
            $vonA = $a->getVon();
            $vonB = $b->getVon();

            if ($vonA instanceof \DateTime && $vonB instanceof \DateTime) {
                return $vonA <=> $vonB;
            }

            // Fallback, falls die Werte nicht vergleichbar sind
            return 0;
        });

        return new ArrayCollection($block);
    }

    /**
     * @return Collection|Zeitblock[]
     */
    public function getRealBeworben(): Collection
    {
        $block = array();
        foreach ($this->beworben->toArray() as $data) {
            if (!$data->getDeleted()) {
                $block[] = $data;
            }
        }

        usort($block, function (Zeitblock $a, Zeitblock $b) {
            return ($a->getVon() > $b->getVon() ? true : false);
        });

        return new ArrayCollection($block);
    }

    public function addZeitblock(Zeitblock $zeitblock): self
    {
        if (!$this->zeitblocks->contains($zeitblock)) {
            $this->zeitblocks[] = $zeitblock;
            $zeitblock->addKind($this);
        }

        return $this;
    }

    public function removeZeitblock(Zeitblock $zeitblock): self
    {
        if ($this->zeitblocks->contains($zeitblock)) {
            $this->zeitblocks->removeElement($zeitblock);
            $zeitblock->removeKind($this);
        }

        return $this;
    }

    /**
     * @return Collection|Abwesend[]
     */
    public function getAbwesends(): Collection
    {
        return $this->abwesends;
    }

    public function addAbwesend(Abwesend $abwesend): self
    {
        if (!$this->abwesends->contains($abwesend)) {
            $this->abwesends[] = $abwesend;
            $abwesend->setKind($this);
        }

        return $this;
    }

    public function removeAbwesend(Abwesend $abwesend): self
    {
        if ($this->abwesends->contains($abwesend)) {
            $this->abwesends->removeElement($abwesend);
            // set the owning side to null (unless already changed)
            if ($abwesend->getKind() === $this) {
                $abwesend->setKind(null);
            }
        }

        return $this;
    }

templates/pdf/agb.html.twig
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
</head>
<body>
<h1>{{ 'Vertragsbedingungen'|trans }}</h1>
{%if text is not null%}
{{ text|markdown_to_html|raw}}
{%endif%}
</body>
</html>

templates/pdf/checkInAusweis.html.twig
<style>
    table {
        border: 1px solid black;

        font-weight: bold;
        margin: 10px;
    }

    td {
        margin: 5px;
    }
</style>
<h2>{% trans %}Checkin Ausweis{% endtrans %}</h2>
{% set farbe = kind.schule.organisation.stadt.hauptfarbe is not empty?kind.schule.organisation.stadt.hauptfarbe:'#61EDF1' %}

<table cellpadding="8px" width="190px">
    <tr >
        <td align="center" style="height: 50px" colspan="2"><span style="font-size: 12px">{{ kind.schule.name }}</span></td>
    </tr>
    <tr style="background-color: {{ farbe }}">
        <td style="height: 30px" colspan="2"><span style="font-size: 10px">{{ kind.schule.organisation.name }}</span></td>
    </tr>
    <tr style="background-color: {{ farbe }}">
        <td style="height: 120px" colspan="2">
        </td>
    </tr>
    <tr style="background-color: {{ farbe }}"><td style="height: 10px"  colspan="2"><span style="font-size: 18px">{{ kind.vorname|upper}}</span></td></tr>
    <tr style="background-color: {{ farbe }}"><td style="height: 15px" colspan="2"><span style="font-size: 15px">{{ kind.nachname}}</span></td></tr>

    <tr style="background-color: {{ farbe }}">
        <td style="height: 15px" colspan="2"><span style="font-size: 10px" >{{ kind.schule.organisation.stadt.name}}</span></td>
    </tr>
</table>

templates/pdf/eltern.html.twig
<style>
    td {
        border-bottom: 1px solid black;
        font-weight: bold;
        margin: 10px;
    }

    tr {
        margin: 5px;
    }
</style>
<h2>{% trans %}Zusammenfassung{% endtrans %}</h2>


<h3>{% trans %}Daten des Erziehungsberechtigten{% endtrans %}</h3>


<table cellpadding="5px">
    <tbody>
    <tr>
        <td>{% trans %}Name des Erziehungsberechtigten{% endtrans %}</td>
        <td>{{ eltern.vorname }} {{ eltern.name }}</td>
    </tr>
    <tr>
        <td>{% trans %}Diese Daten gelten ab dem{% endtrans %}</td>
        <td>{{ eltern.startDate|date('d.m.Y') }}</td>
    </tr>
    <tr>
        <td>{% trans %}Adresse des Erziehungsberechtigten{% endtrans %}</td>
        <td>{{ eltern.strasse }}<br>{{ eltern.plz }} {{ eltern.stadt }}</td>
    </tr>
    <tr>
        <td>{{ 'Telefonnummer'|trans }}</td>
        <td>{{ eltern.phoneNumber }}</td>
    </tr>

    {% set stadt = kind.schule.stadt %}

    <tr>
        <td>{% trans %}Berufliche Situation des Erziehungsberechtigten{% endtrans %}</td>
        <td>{{ beruflicheSituation[eltern.beruflicheSituation] }}</td>
    </tr>
    <tr>
        <td>{% trans %}Kontakt für evtl. Notfälle{% endtrans %}</td>
        <td>{{ eltern.notfallName }}</td>
    </tr>
    <tr>
        <td>{% trans %}Telefonnummer für evtl. Notfälle{% endtrans %}</td>
        <td>{{ eltern.notfallkontakt }}</td>
    </tr>
    <tr>
        <td>{% trans %}Weitere abholberechtigte Personen{% endtrans %}</td>
        <td>{{ eltern.abholberechtigter }}</td>
    </tr>
    <tr>
        <td>{% trans %}Bankverbindung für Lastschrift{% endtrans %}</td>
        <td>{{ eltern.kontoinhaber }}<br/>{{ eltern.iban }}<br/>{{ eltern.bic }}
            <br/>{{ eltern.sepaInfo?"Ich erteile der betreuenden Organisation (den betreuenden Organisationen) ein SEPA Lastschrift Mandant für die Dauer des Betreuungsvertrags"|trans:""|trans }}
        </td>
    </tr>
    <tr>
        <td>{% trans %}E-Mail Adresse{% endtrans %}</td>
        <td>{{ eltern.email }}</td>
    </tr>
    {% if kind is defined and kind is not null %}
        <tr>
            <td>{% trans %}Monatliche Gebühren{% endtrans %}</td>
            <td>{{ getPreisforBetreuungWithoutBeworben(kind,kind.startDate)|number_format(2,',','.') }} €</td>
        </tr>
    {% endif %}
    {% if eltern.secCode is not null %}
        <tr>
            <td>{% trans %}Sicherheitscode (Dieser Code wird bei jeder Kommunikation mit dem Träger abgefragt){% endtrans %}</td>
            <td>{{ eltern.secCode }}</td>
        </tr>
    {% endif %}
    <tr>
        <td colspan="2">
            <h5>{{ 'Weitere Informationen'|trans }}</h5>
        </td>
    </tr>
    {% include 'widget/__elternTabelle_Vollstandig.html.twig' with {'stadt':stadt,'eltern':eltern} %}
    </tbody>
</table>

templates/pdf/elternOrganisation.html.twig
<style>
    td {
        border-bottom: 1px solid black;
        font-weight: bold;
        margin: 10px;
    }

    tr {
        margin: 5px;
    }
</style>

<h3>{% trans %}Daten des Erziehungsberechtigten{% endtrans %}</h3>


<table cellpadding="5px">
    <tbody>
    <tr>
        <td>{% trans %}Name des Erziehungsberechtigten{% endtrans %}</td>
        <td>{{ eltern.vorname }} {{ eltern.name }}</td>
    </tr>
    <tr>
        <td>{% trans %}E-Mail Adresse{% endtrans %}</td>
        <td>{{ eltern.email }}</td>
    </tr>
    <tr>
        <td>{% trans %}Telefonnummer{% endtrans %}</td>
        <td>{{ eltern.phoneNumber }}</td>
    </tr>
    <tr>
        <td>{% trans %}Adresse des Erziehungsberechtigten{% endtrans %}</td>
        <td>{{ eltern.strasse }}<br>{{ eltern.plz }} {{ eltern.stadt }}</td>
    </tr>
    {% if is_granted('ROLE_ORG_ACCOUNTING') %}
        {% include 'widget/__elternTabelle_Vollstandig.html.twig' with {'stadt':getStadtFromEltern(eltern),'eltern':eltern} %}
    {% else %}
        {% include 'widget/__elternTabelle_reduced.html.twig' with {'stadt':getStadtFromEltern(eltern),'eltern':eltern} %}
    {% endif %}
    <tr>
        <td>{% trans %}Name des Notfallkontakt{% endtrans %}</td>
        <td>{{ eltern.notfallName }}</td>
    </tr>
    <tr>
        <td>{% trans %}Notfallkontakt{% endtrans %}</td>
        <td>{{ eltern.notfallkontakt }}</td>
    </tr>
    <tr>
        <td>{% trans %}Weitere abholberechtigte Personen{% endtrans %}</td>
        <td>{{ eltern.abholberechtigter|nl2br }}</td>
    </tr>


    </tbody>
</table>


<!-- Daten der Kinder in einer for Schleife -->

templates/pdf/img.html.twig
{{ vich_uploader_asset(stadt, 'imageFile') }}

templates/pdf/kind.html.twig
<style>
    td {
        border: 1px solid black;

        font-weight: bold;
        margin: 10px;
    }

    tr {
        margin: 5px;
    }
</style>
<h2>{% trans %}Zusammenfassung{% endtrans %} SKiB</h2>
{% set eltern = getEltern(kind,kind.startDate) %}

<h3>{{ kind.vorname }} {{ kind.nachname }} | {% trans %}Geburtstag{% endtrans %}: {{ kind.geburtstag|date('d.m.Y') }}
    | {% trans %}Klasse{% endtrans %}: {{ kind.klasseString }}</h3>
    <h3>{{ 'Betreuungsbeginn mit diesem Stundenplan'|trans }}: {{ kind.startDate|date('d.m.Y') }}</h3>
{% if not kind.schule.stadt.hideChildQuestions %}
    <p>{{ 'Allergie'|trans }}: {{ kind.allergie }} | {{ 'Medikamente'|trans }}: {{ kind.medikamente }}
        {% endif %}
        | {{ 'Sicherheitscode'|trans }}: {{ eltern.secCode }} | {{ 'Monatliche Gebühren'|trans }}
        : {{ getPreisforBetreuungWithoutBeworben(kind,kind.startDate)|number_format(2,',','.') }}€</p>

    <table cellpadding="3px">
        <thead>
        <tr>
            <th>{{ 'Montag'|trans }}</th>
            <th>{{ 'Dienstag'|trans }}</th>
            <th>{{ 'Mittwoch'|trans }}</th>
            <th>{{ 'Donnerstag'|trans }}</th>
            <th>{{ 'Freitag'|trans }}</th>
            <th>{{ 'Samstag'|trans }}</th>
            <th>{{ 'Sonntag'|trans }}</th>
        </tr>
        </thead>
        <tbody>
        {{ table|raw }}
        </tbody>
    </table>

templates/pdf/kindOrganisation.html.twig
<style>
    td {
        border: 1px solid black;

        font-weight: bold;
        margin: 10px;
    }

    tr {
        margin: 5px;
    }
</style>
<h2>{% trans %}Zusammenfassung{% endtrans %} SKiB</h2>
<h2>{% trans %}Daten des Kindes{% endtrans %}: {{ k.vorname }} {{ k.nachname }}</h2>

<table cellpadding="5px">
    <tbody>
    <tr>
        <td>{% trans %}Vorname{% endtrans %}</td>
        <td>{{ k.vorname }}</td>
    </tr>
    <tr>
        <td>{% trans %}Nachname{% endtrans %}</td>
        <td>{{ k.nachname }}</td>
    </tr>
    <tr>
        <td>{% trans %}Geburtstag{% endtrans %}</td>
        <td>{{ k.geburtstag|date('d.m.Y') }}</td>
    </tr>
    <tr>
        <td>{% trans %}Schule{% endtrans %}</td>
        <td>{{ k.schule.name }}</td>
    </tr>
    <tr>
        <td>{% trans %}Klasse{% endtrans %}</td>
        <td>{{ k.klasseString }}</td>
    </tr>
    <tr>
        <td>{% trans %}Mein Kind ist gegen Masern geimpft / bereits immun{% endtrans %}</td>
        <td>{{ k.masernImpfung?"Ja"|trans:'Nein'|trans }}</td>
    </tr>
    {% if not k.schule.stadt.hideChildQuestions %}
        <tr>
            <td>{% trans %}Allergien{% endtrans %}</td>
            <td>{{ k.allergie }}</td>
        </tr>
        <tr>
            <td>{% trans %}Medikamente{% endtrans %}</td>
            <td>{{ k.medikamente }}</td>
        </tr>

        <tr>
            <td>{% trans %}Mein Kind ist glutenintolerant{% endtrans %}</td>
            <td>{{ k.gluten?'Ja'|trans:'Nein'|trans }}</td>
        </tr>
        <tr>
            <td>{% trans %}Mein Kind ist laktoseintolerant{% endtrans %}</td>
            <td>{{ k.laktose?'Ja'|trans:'Nein'|trans }}</td>
        </tr>
        <tr>
            <td>{% trans %}Mein Kind isst kein Schweinefleisch{% endtrans %}</td>
            <td>{{ k.schweinefleisch?'Ja'|trans:'Nein'|trans }}</td>
        </tr>
        <tr>
            <td>{% trans %}Mein Kind ernährt sich vegetarisch{% endtrans %}</td>
            <td>{{ k.vegetarisch?'Ja'|trans:'Nein'|trans }}</td>
        </tr>
        <tr>
            <td>{% trans %}Mein Kind darf nach Ende der gebuchten Betreuung alleine nach Hause{% endtrans %}</td>
            <td>{{ k.alleineHause?'Ja'|trans:'Nein'|trans }}</td>
        </tr>
        <tr>
            <td>{% trans %}Mein Kind darf an Ausflügen teilnehmen{% endtrans %}</td>
            <td>{{ k.ausfluege?'Ja'|trans:'Nein'|trans }}</td>
        </tr>
        {% if k.schule.stadt.settingsSkibShowSonnencremeKinder != true %}
            <tr>
                <td>{% trans %}Mein Kind darf im Sommer mit handelsüblicher Sonnencreme eingecremt werden{% endtrans %}</td>
                <td>{{ k.sonnencreme?'Ja'|trans:'Nein'|trans }}</td>
            </tr>
        {% endif %}
        {% if k.schule.stadt.settingsSkibShowZeckenKinder != true %}
            <tr>
                <td>{% trans %}Betreuer dürfen bei meinem Kind Zecken entfernen{% endtrans %}</td>
                <td>{{ k.zeckenEntfernen?"Ja"|trans:'Nein'|trans }}</td>
            </tr>
        {% endif %}
        <tr>
            <td>{% trans %}Fotos, auf welchen mein Kind zu sehen ist, dürfen sowohl in der öffentlichen Presse veröffentlicht, als auch für die Öffentlichkeitsarbeit der betreuenden Organisationen genutzt werden.{% endtrans %}</td>
            <td>{{ k.fotos?'Ja'|trans:'Nein'|trans }}</td>
        </tr>
    {% endif %}
    <tr>
        <td>
            {{ 'Beginn der Betreuung:'|trans }}
        </td>
        <td>
            {{ k.startDate|date('d.m.Y') }}
        </td>
    </tr>
    {% if k.betreungsblocksReal|length > 0 %}
        <tr>
            <td>{% trans %}Bemerkung{% endtrans %}</td>
            <td>{{ k.bemerkung }}</td>
        </tr>

        <tr>
            <td>
                {% trans %}Gebuchte Betreuungszeitfenster{% endtrans %}
            </td>


            <td>
                <ul class="list-group">
                    {% for day in zeitblock %}
                        <li><b>{{ day[0].wochentagString }}</b></li>
                        {% for z in day %}
                            <li class="list-group-item"> {{ z.von|date('H:i') }}
                                - {{ z.bis|date('H:i') }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </td>
        </tr>
    {% endif %}
    {% if k.betreungsblocksRealKontingent|length > 0 %}
        <tr>
            <td>
                {% trans %}Angemeldete Betreuungszeitfenster{% endtrans %}
            </td>

            <td>
                <ul class="list-group">
                    {% for day in beworben %}
                        <li><b>{{ day[0].wochentagString }}</b></li>
                        {% for z in day %}
                            <li class="list-group-item"> {{ z.von|date('H:i') }}
                                - {{ z.bis|date('H:i') }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </td>
        </tr>
    {% endif %}


    </tbody>
</table>


<!-- Daten der Kinder in einer for Schleife -->

templates/pdf/kinderliste.html.twig
<style>
    td {
        border: 1px solid black;
        font-weight: bold;
        margin: 10px;
    }

    tr {
        margin: 5px;
    }
</style>
<h2>{{ text }}</h2>


<table class="table table-hover" cellpadding="3px">
    <thead>
    <tr>
        <th>{{ 'Anwesend'|trans }}</th>
        <th>{% trans %}Vorname{% endtrans %}</th>
        <th>{% trans %}Nachname{% endtrans %}</th>
        <th>{% trans %}Notfallkontakt{% endtrans %}</th>
        {% if schulen|length > 1 %}
            <th>{% trans %}Schule{% endtrans %}</th>
        {% endif %}
        <th>{% trans %}Klasse{% endtrans %}</th>
        <th>{% trans %}Alleine nach Hause{% endtrans %}</th>
        {% if 0 in wochentag %}
            <th>{% trans %}Mo{% endtrans %}</th>
        {% endif %}
        {% if 1 in wochentag %}
            <th>{% trans %}Di{% endtrans %}</th>
        {% endif %}
        {% if 2 in wochentag %}
            <th>{% trans %}Mi{% endtrans %}</th>
        {% endif %}
        {% if 3 in wochentag %}
            <th>{% trans %}Do{% endtrans %}</th>
        {% endif %}
        {% if 4 in wochentag %}
            <th>{% trans %}Fr{% endtrans %}</th>
        {% endif %}
        {% if is_granted('ROLE_ORG_VIEW_NOTICE') %}
            <th>{% trans %}Notizen{% endtrans %}</th>
        {% endif %}

    </tr>
    </thead>
    <tbody>
    {% for k in kinder %}
        {% set eltern = getEltern(k,stichtag?:date()) %}
        <tr>
            <td></td>
            <td>{{ k.vorname }}</td>
            <td>{{ k.nachname }}</td>
            <td>{{ eltern.notfallkontakt }}</td>
            {% if schulen|length > 1 %}
                <td>{{ k.schule.name }}</td>
            {% endif %}
            <td>{{ k.klasseString }}</td>
            <td>{{ k.alleineHause?'Ja'|trans:'Nein'|trans }}</td>

            {% if 0 in wochentag %}
                <td>{{ getStringForBlocks(k,0)|nl2br }}</td>
            {% endif %}
            {% if 1 in wochentag %}
                <td>{{ getStringForBlocks(k,1)|nl2br }}</td>
            {% endif %}
            {% if 2 in wochentag %}
                <td>{{ getStringForBlocks(k,2)|nl2br }}</td>
            {% endif %}
            {% if 3 in wochentag %}
                <td>{{ getStringForBlocks(k,3)|nl2br }}</td>
            {% endif %}
            {% if 4 in wochentag %}
                <td>{{ getStringForBlocks(k,4)|nl2br }}</td>
            {% endif %}
            {% if is_granted('ROLE_ORG_VIEW_NOTICE') %}
                <td>{{ k.internalNotice|raw }}</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>


<!-- Daten der Kinder in einer for Schleife -->